
```{r DA-RT-zone-{{zone.name}}-{{period.name}}, results='asis', include=TRUE}
z.name = '{{zone.name}}' # Assign zone name
p.name = '{{period.name}}' # Assign period name
cat("### ", p.name, ': ', z.name) # Print period and zone name above the plot
text.plot=11 # Plot text size.
figure.width = 9
figure.height = 6
```

```{r DA-RT-plot-zone-{{zone.name}}-{{period.name}}, fig.width=figure.width, fig.height=figure.height, include=TRUE}
# Check to make sure this zone shouldn't be ignored
if ( !z.name %in% ignore.zones ) {
  
  # Pull out only the data for the generation types specified in the input file and the current zone and period. Summarise by zone.
  plot.data = plot.data.all[Type %in% da.rt.types & Zone==z.name & Period==p.name, 
                            .(RT.gen = sum(RT.gen), RT.cap = sum(RT.cap), DA.cap = sum(DA.cap)), 
                            by=.(Zone, time, Type, Period)]
  
  # Assign the order which the generation types will appear in the plot.
  plot.data[, Type := factor(Type, levels=rev(gen.order))]
  
  # this is just for scaling the y-axis (either by load or generation, whichever is bigger)
  stack.r = plot.data[Period==p.name & Zone==z.name, .(value=sum(DA.cap)), by=.(time)]

  # Check that there is actually generation data to plot, otherwise don't make a plot.
  if ( length(stack.r$value)>0 & sum(stack.r$value)>0 ) {

    blank_data = plot.data[, .(ylim=sum(RT.cap)/1000*1.06), by=.(time,Type)]
    plot.data[, lt:="DA Committed Capacity or \nForecasted Generation"]
    
    # Create plot
    ggplot()+geom_area(data=plot.data, aes(time, RT.gen/1000, fill=Type), alpha=0.4)+
      geom_line(data=plot.data[Type != 'Hydro', ], aes(time, RT.cap/1000, color=Type), size=1)+
      geom_line(data=plot.data[Type != 'Hydro', ], aes(time, DA.cap/1000, linetype=lt), color="grey50", size=1, alpha=0.5)+
      geom_blank(data=blank_data, aes(x=time, y=ylim))+
      expand_limits(y=0)+
      scale_linetype_manual("",values=c(1,1))+
      scale_fill_manual("RT Generation", values = gen.color)+
      scale_x_datetime(breaks = date_breaks(width = "1 day"), labels = date_format("%b %d\n%I %p"), expand = c(0, 0))+
      scale_y_continuous(label=comma, expand=c(0,0))+
      scale_color_manual("RT Committed Capacity", values = gen.color)+
      ylab("Generation or Online Capacity (GW)")+xlab(NULL)+
  #     guides(color = guide_legend(order=1), fill = guide_legend(order=2, reverse=TRUE))+
      theme(legend.key = element_rect(color = "grey70", size = 0.8),
            legend.key.size = grid::unit(1.5, "lines"), 
            legend.text = element_text(size=text.plot), 
            text=element_text(size=text.plot), 
            strip.text=element_text(face=1, 
                                    size=rel(0.8)), 
            axis.text.x=element_text(size=text.plot/1.8), 
            axis.text.y=element_text(size=text.plot/1.2), 
            axis.title=element_text(size=text.plot, face=2),
            panel.grid.major = element_line(colour = "grey85"),
            panel.grid.minor = element_line(colour = "grey93"),
            panel.margin = unit(0.45, "lines"))+facet_grid(Type~., scales="free_y")
    
  }
}
```