
```{r key-period-dispatch-region-{{period.name}}-{{region.name}}, results='asis', include=TRUE}
p.name = '{{period.name}}' # Set key period name
r.name = '{{region.name}}' # Set region name
cat("### ", p.name, ': ', r.name) # Print out key period and region name above plot
text.plot=11
figure.width = 9
figure.height = 6
```

```{r key-period-dispatch-plots-region-{{period.name}}-{{region.name}}, fig.width=figure.width, fig.height=figure.height, include=TRUE}

# ###############################################################################
# Region plot height
# ###############################################################################  

# this is just for scaling the y-axis (either by load or generation, whichever is bigger)
stack.r = gen.type.region[Period==p.name & Region==r.name, .(value = sum(value)), by=.(time)]
# stack.r$Type = "ALL"

# Check to make sure there is actually generation data for this region. If not, no plot is crated.
if ( length(stack.r$value)>0 & sum(stack.r$value)>0 ) {
  
  # If load is larger than generation, reassign the y-axis height so load isn't cut off.
  if (max(gen.load[Period==p.name & Region==r.name, value])>max(stack.r$value)){
    stack.r = gen.load[Period==p.name & Region==r.name, .(value=sum(value)), by=.(time)]
  }

  # This automatically creates the y-axis scaling
  py.r  =pretty(stack.r$value/1000, n = 4)
  seq.py.r = seq(0, py.r[length(py.r)], 2*(py.r[2]-py.r[1])) # get whole breaks sequence
  
  # #############################################################################################################
  # Region plots
  # #############################################################################################################
  ggplot(gen.type.region[Period==p.name & Region==r.name, ], aes(time, value/1000, group=Type, fill=Type, order=as.numeric(Type)), color="black")+
        geom_area(color=NA)+
        geom_line(position="stack", size=0.3)+
        labs(y="Generation (GWh)", x=NULL)+
        geom_line(data=gen.load.region[Period==p.name & Region==r.name, ], linetype="longdash", aes(color="load"),size=0.8)+
        scale_fill_manual("",values = gen.color, limits=rev(gen.order))+
        scale_color_manual(name='', values=c("load"="grey40"), labels=c("Load"))+
        scale_x_datetime(breaks = date_breaks(width = "1 day"), labels = date_format("%b %d\n%I %p"), expand = c(0, 0))+
        scale_y_continuous(breaks=seq.py.r, limits=c(0, max(py.r)), expand=c(0,0))+
        theme(legend.key = element_rect(color = "grey80", size = 0.4),
              legend.key.size = grid::unit(0.9, "lines"), 
              legend.text = element_text(size=text.plot/1.1),
              strip.text=element_text(size=rel(0.7)),
              axis.text=element_text(size=text.plot/1.2), 
              axis.title=element_text(size=text.plot, face=2), 
              axis.title.x=element_text(vjust=-0.3),
              panel.grid.major = element_line(colour = "grey85"),
              panel.grid.minor = element_line(colour = "grey93"),
              aspect.ratio = 0.5)

} else { print('No generation found for this period and region.')}
```



  
  