---
title: "Multi-area Grid Metrics Analyzer\nFlexibility Inventory"
author: "Created by: `r Sys.info()['user']`"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    css: custom.css
    toc: yes
---

```{r setOptions, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Set up default options for chunks, turn off error or warning messages.
knitr::opts_chunk$set(echo=FALSE, comment=NA, warning=FALSE, message=FALSE, include=TRUE,
                      fig.path=fig.path.name, dev='png', fig.width=12)

if (!exists('wrap.cols')){
  wrap.cols = 3 #number of facet columns for wrapping
}
# Set dynamic height for figures
g.height = ( length(unique(gen.type.mapping)) %/% wrap.cols + 
               length(unique(gen.type.mapping)) %% wrap.cols ) * 3
s.height = ( length(db.loc) ) * 4
s.width = ( length(db.loc) %/% 3 + length(db.loc) %% wrap.cols ) * 10
p.height = ( length(period.names) %/% 2 + length(period.names) %% 2 ) * 5
t.height = ( length(re.types) ) * 5
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

### Data below generated for:
"`r gsub('.*Model', 'Model', db$filename)`"

***
## Net Load 
***
```{r net-load}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
source('source_scripts/f_netload.R')
print(p.nl) 
  # theme(aspect.ratio = 2.5/length(db.loc),
  #       axis.text.x = element_text(angle = -30, hjust = 0),
  #       text = element_text(face='bold')))


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

## Diurnal Net Load

```{r diurnal-net-load}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
source('source_scripts/f_netload.R')
print(p.nlv)
  # theme(aspect.ratio = 2.5/length(db.loc),
  #       axis.text.x = element_text(angle = -30, hjust = 0),
  #       text = element_text(face='bold')))
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

## Net Load Duration

```{r net-load-duration}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
source('source_scripts/f_netload.R')
print(p.dur)#+
#   theme(aspect.ratio = 2.5/length(db.loc),
#         axis.text.x = element_text(angle = -30, hjust = 0),
#         text = element_text(face='bold')))

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
```{r net-load-duration-curtailment}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
print(p.durbar) # +
      # theme(aspect.ratio = 2.5/length(db.loc),
      #       axis.text.x = element_text(angle = -30, hjust = 0),
      #       text = element_text(face='bold')))
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

## Net Load Ramps

### Net Load Ramp Histogram

```{r net-load-ramp-histogram}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
source('source_scripts/f_netload_ramps.R')
for(i in flex.intervals){
#    cat("###",i, "\n")
    i_name = gsub(" ","",i)
    print(get(sprintf("p%s",i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

### Net Load Ramp Seasonal Duration

```{r net-load-ramp-duration}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
#    cat("###",i, "\n")
    i_name = gsub(" ","",i)
    print(get(sprintf("pp%s",i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

### Net Load Ramp Statistics

```{r net-load-ramp-statistics, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    cat("####",i, "Flex Inventory\n")
    i_name = gsub(" ","",i)
    print(kable(get(sprintf("up_%s",i_name)), format.args = list(big.mark = ','), digits = 2, caption = 'Net Load Up Ramps')) 
    cat("\n")
    print(kable(get(sprintf("down_%s",i_name)), format.args = list(big.mark = ','), digits = 2, caption = 'Net Load Down Ramps')) 
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


### Worst Ramp Ups

```{r worst-ramp-ups, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in c(1:length(unique(interval.generation$scenario)))){
    i_name = unique(interval.generation$scenario)[i]
    cat("####",unique(interval.generation$scenario)[i])
    print(get(sprintf("p_rect_%s",i_name)))
    cat("\n")

}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


### Worst Ramp Downs

```{r worst-ramp-downs, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in c(1:length(unique(interval.generation$scenario)))){
    i_name = unique(interval.generation$scenario)[i]
    cat("####",unique(interval.generation$scenario)[i])
    print(get(sprintf("p_rect_down_%s",i_name)))
    cat("\n")

}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


### Flexibility Inventory

```{r flexibility-inventory, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
source('source_scripts/f_flexibility_inventory.R')
print(kable(flex.inventory.final.results, format.args = list(big.mark = ','), digits = 0, caption = 'Lowest Flexibility Inventory')) 
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r flexibility-inventory-inv-up, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Inventory Up for %s",i))
    print(get(sprintf("p_invup_%s", i_name)))
    cat("\n")
    }
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r flexibility-inventory-inv-down, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Inventory Down for %s",i))
    print(get(sprintf("p_invdown_%s", i_name)))
    cat("\n")
    }# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


```{r flexibility-inventory-totalflex, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Total Inventory for %s",i))
    print(get(sprintf("p_totalflex_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


```{r flexibility-inventory-durationflexup, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Total Inventory Up for %s",i))
    print(get(sprintf("p_flexup_duration_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


```{r flexibility-inventory-durationflexdown, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Total Inventory Down for %s",i))
    print(get(sprintf("p_flexdown_duration_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


```{r flexibility-inventory-percflex, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Inventory for %s as a Percentage",i))
    print(get(sprintf("p_percflex_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r flexibility-inventory-diurnalflex, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Total Average Daily Inventory for %s",i))
    print(get(sprintf("p_diurnalflex_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r flexibility-inventory-diurnalup, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Total Average Daily Inventory for %s",i))
    print(get(sprintf("p_diup_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r flexibility-inventory-diurnaldown, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    i_name = gsub(" ","", i)
    cat("####",sprintf("Total Average Daily Inventory for %s",i))
    print(get(sprintf("p_didown_%s", i_name)))
    cat("\n")
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r worst-days-ramp_ability, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    for(j in scenario.names){
        cat("####",sprintf("Resources used to meet largest ramps in %s, %s",i, j))
        print(get(sprintf("p_rampability_%s_%s", j, i)))
        cat("\n")
    }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r diurnal-flexibility, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    for(j in scenario.names){
        cat("####",sprintf("Diurnal Average Flexibility Range in %s, %s",i, j))
        print(get(sprintf("p_diurnal_flexribbon_%s_%s", j, i)))
        cat("\n")
    }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r minup-flexribbon, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    for(j in scenario.names){
        cat("####",sprintf("Lowest Upward Flexibility Period in %s, %s",i, j))
        print(get(sprintf("p_minup_flexribbon_%s_%s", j, i)))
        cat("\n")
    }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```{r mindown-flexribbon, results = 'asis'}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for(i in flex.intervals){
    for(j in scenario.names){
        cat("####",sprintf("Lowest Downward Flexibility Period in in %s, %s",i, j))
        print(get(sprintf("p_mindown_flexribbon_%s_%s", j, i)))
        cat("\n")
    }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
