
```{r key-period-dispatch-scen-region-{{period.name}}-{{region.name}}, results='asis', include=TRUE}
p.name = '{{period.name}}' # Set key period name
r.name = '{{region.name}}' # Set region name
cat("### ", p.name, ': ', r.name) # Print out key period and region name above plot
text.plot=11
figure.width = 9
figure.height = s.height
```

```{r key-period-dispatch-scen-plots-region-{{period.name}}-{{region.name}}, fig.width=figure.width, fig.height=figure.height, include=TRUE}

# ###############################################################################
# Region plot height
# ###############################################################################  

# Check to make sure there is actually generation data for this region. If not, no plot is crated.
stack.r = gen.type.region[Period==p.name & Region==r.name, .(value=sum(value)),by=.(scenario,time)]

if ( length(stack.r$value)>0 & sum(stack.r$value)>0 ) {
  
  # If load is larger than generation, reassign the y-axis height so load isn't cut off.
  if (max(gen.load[Period==p.name & Region==r.name, value])>max(stack.r$value)){
    stack.r = gen.load[Period==p.name & Region==r.name, .(value=sum(value)), by=.(scenario,time)]
  }
  
p = dispatch_plot(gen.type.region[Period==p.name & Region==r.name,],
                  gen.load.region[Period==p.name & Region==r.name,])

print(p + facet_wrap(~scenario, ncol = 1))
  
} else { print('No generation found for this period and region.')}
```




